version: 2

references:
# ----------------------------
# Cache Configuration
# ----------------------------
  cache_key: &cache_key
    key: cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
  restore_dependency_cache: &restore_dependency_cache
    restore_cache:
      <<: *cache_key
  save_dependency_cache: &save_dependency_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle
        - ~/.m2

# ----------------------------
# Docker Configuration
# ----------------------------
  android_config: &android_config
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3g
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" -Dkotlin.compiler.execution.strategy=“in-process” -Dkotlin.daemon.jvm.options=-Xmx2g'

  # Workspace
  workspace: &workspace
    ~/code

jobs:

## Build debug APK
  build_debug:
    <<: *android_config
    steps:
      - checkout
      - *restore_dependency_cache
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies  --no-daemon
      - *save_dependency_cache
      - run:
          name: Gradle build (debug)
          command: ./gradlew assembleDebug --no-daemon  -Pkotlin.incremental=false
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: /apk/

  ## Run Lint and Unit Tests
  test_unit:
    <<: *android_config
    steps:
      - checkout
      - *restore_dependency_cache
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies --no-daemon
      - *save_dependency_cache
      - run:
          name: Run Lint and Tests
          command: ./gradlew lintDebug testDebugUnitTest -Pkotlin.incremental=false
      - store_artifacts:
          path: app/build/reports/
          destination: /reports/
      - store_test_results:
          path: app/build/test-results/
          destination: /test-results/

# see https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
# goal is to BUILD & TEST for all branches & all tags
#         to DEPLOY only for tags against master marked with a version number
workflows:
  version: 2
  all_flavours:
    jobs:
      - build_debug:
          filters:
            tags:
              only: /.*/

      - test_unit:
          filters:
            tags:
              only: /.*
          requires:
            - build_debug